import { useEffect } from "react";
import { Link } from "wouter";
import { ArrowRight, Check, ChevronDown, ClipboardCheck, Droplets, FileText, Home as HomeIcon, LocateFixed, Microscope, Phone, ShieldCheck, Sparkles, Wind } from "lucide-react";
import Seo from "@/components/Seo";
import { DISPLAY_PHONE, PHONE } from "@/components/SiteShell";

const heroImage = "/manus-storage/sactown-hero_40fc0dc3.jpg";
const inspectionImage = "/manus-storage/sactown-inspection-detail_842490f2.jpg";
const airImage = "/manus-storage/sactown-air-quality_caf7ba3d.jpg";

const localBusinessSchema = { "@context": "https://schema.org", "@type": "ProfessionalService", name: "Sactown Mold's Inspections", url: "https://www.moldinspectionsacramentoca.com/", telephone: DISPLAY_PHONE, address: { "@type": "PostalAddress", streetAddress: "2848 Arden Wy", addressLocality: "Sacramento", addressRegion: "CA", postalCode: "95825", addressCountry: "US" }, areaServed: ["Sacramento", "Midtown Sacramento", "East Sacramento", "Arden-Arcade", "Citrus Heights", "Elk Grove", "Roseville", "Folsom", "Fair Oaks" ], priceRange: "$$" };
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: ["What does a mold inspection include?", "Do you offer mold testing?", "How quickly can I schedule an inspection?"].map((name, index) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text: ["A visual review, moisture investigation, accessible area checks, photo documentation, and a clear written summary tailored to the property.", "When sampling is useful for the question at hand, we can discuss appropriate air or surface sampling as part of the inspection plan.", "Call the inspection desk at +1 916-665-4249 to discuss timing, property type, and the concern you want investigated."][index] } })) };

const services = [
  { icon: Microscope, title: "Mold inspection", copy: "A structured look at visible conditions, moisture patterns, and areas that deserve a closer read.", href: "/mold-inspection-sacramento-ca", accent: "sage" },
  { icon: Wind, title: "Indoor air quality", copy: "Understand the air in your home with practical testing conversations and evidence you can use.", href: "/indoor-air-quality-sacramento-ca", accent: "clay" },
  { icon: Droplets, title: "Moisture inspection", copy: "Trace the conditions that can support mold growth — from leaks and intrusion to humidity.", href: "/moisture-inspection-sacramento-ca", accent: "sand" },
  { icon: FileText, title: "Clear reporting", copy: "Get findings organized into a useful report with photos, context, and next-step options.", href: "/mold-inspection-report-sacramento-ca", accent: "sage" },
];

const areas = ["Midtown Sacramento", "East Sacramento", "Arden-Arcade", "Citrus Heights", "Elk Grove", "Roseville", "Folsom", "Fair Oaks"];

export default function Home() {
  useEffect(() => { document.documentElement.style.scrollBehavior = "smooth"; return () => { document.documentElement.style.scrollBehavior = "auto"; }; }, []);
  return <>
    <Seo title="Mold Inspection in Sacramento, CA | Sactown Mold's Inspections" description="Professional mold inspection, moisture investigation, and indoor air quality services in Sacramento, CA. Get a clear plan from Sactown Mold's Inspections." path="/" schema={[localBusinessSchema, faqSchema]} />
    <section className="relative isolate overflow-hidden bg-[#19352d] text-[#f6f5f0]">
      <div className="absolute inset-0"><img src={heroImage} alt="Inspector using a moisture meter inside a Sacramento home" className="h-full w-full object-cover object-center opacity-65" /><div className="absolute inset-0 bg-gradient-to-r from-[#102a24] via-[#19352d]/88 to-[#19352d]/25" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_15%,rgba(217,166,106,.18),transparent_32%)]" /></div>
      <div className="container relative grid min-h-[670px] items-end gap-12 py-20 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:py-28">
        <div className="max-w-3xl">
          <div className="eyebrow text-[#d9a66a]"><span className="h-px w-8 bg-[#d9a66a]" /> Sacramento indoor-environment specialists</div>
          <h1 className="mt-7 max-w-3xl font-display text-5xl font-semibold leading-[.98] tracking-[-0.065em] text-balance sm:text-6xl lg:text-8xl">Mold inspection in Sacramento, with a clearer point of view.</h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-[#d5e0d5] sm:text-xl">When a space feels off, you need more than a quick glance. We investigate the visible conditions, moisture story, and indoor environment — then explain what the evidence means.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={`tel:${PHONE}`} className="button-accent justify-center"><Phone size={17} /> Call now · {DISPLAY_PHONE}</a><a href="#services" className="button-ghost justify-center">Explore inspections <ArrowRight size={17} /></a></div>
          <div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold uppercase tracking-[.14em] text-[#c1d1c3]"><span className="inline-flex items-center gap-2"><Check size={14} className="text-[#d9a66a]" /> Clear written findings</span><span className="inline-flex items-center gap-2"><Check size={14} className="text-[#d9a66a]" /> Photo-supported observations</span></div>
        </div>
        <div className="hidden lg:block"><div className="ml-auto max-w-sm rounded-[28px] border border-white/20 bg-[#f6f5f0]/10 p-5 shadow-2xl backdrop-blur-md"><div className="rounded-[22px] bg-[#f6f5f0] p-6 text-[#19352d]"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.2em] text-[#6d7d72]">Inspection desk</span><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#e6ebe4] text-[#19352d]"><ShieldCheck size={17} /></span></div><div className="mt-10 font-display text-3xl font-semibold tracking-[-.045em]">Start with the question.</div><p className="mt-3 text-sm leading-6 text-[#627269]">Tell us what you are seeing, smelling, or planning. We&apos;ll help you choose the right inspection path.</p><a href={`tel:${PHONE}`} className="mt-7 flex items-center justify-between rounded-2xl bg-[#19352d] px-4 py-4 text-sm font-bold text-white">Speak with an inspector <ArrowUpRightIcon /></a></div></div></div>
      </div>
      <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-[#f6f5f0] to-transparent" />
    </section>

    <section className="border-b border-[#19352d]/10 bg-[#f6f5f0]"><div className="container grid gap-6 py-9 sm:grid-cols-3"><div className="flex items-start gap-4"><span className="stat-icon"><HomeIcon size={19} /></span><div><div className="font-display text-xl font-semibold">Residential & commercial</div><p className="mt-1 text-sm text-[#6d7d72]">A right-sized inspection for the property and the question.</p></div></div><div className="flex items-start gap-4"><span className="stat-icon"><LocateFixed size={19} /></span><div><div className="font-display text-xl font-semibold">Sacramento-based</div><p className="mt-1 text-sm text-[#6d7d72]">Serving the city and nearby communities with local context.</p></div></div><div className="flex items-start gap-4"><span className="stat-icon"><ClipboardCheck size={19} /></span><div><div className="font-display text-xl font-semibold">A useful next step</div><p className="mt-1 text-sm text-[#6d7d72]">Findings organized for homeowners, buyers, sellers, and teams.</p></div></div></div></section>

    <section className="section-pad"><div className="container grid items-center gap-14 lg:grid-cols-[.92fr_1.08fr] lg:gap-24"><div className="relative"><div className="absolute -left-7 -top-7 h-28 w-28 rounded-full border border-[#d9a66a]/55" /><img src={inspectionImage} alt="Close-up of inspection tools and moisture meter" className="relative aspect-[4/3] w-full rounded-[28px] object-cover shadow-[0_25px_70px_rgba(25,53,45,.16)]" /><div className="absolute -bottom-7 right-5 max-w-[210px] rounded-2xl bg-[#d9a66a] p-5 text-[#19352d] shadow-xl"><div className="text-xs font-bold uppercase tracking-[.16em]">The goal</div><div className="mt-2 font-display text-xl font-semibold leading-tight">Less guessing. More useful information.</div></div></div><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> Why Sactown Mold&apos;s</div><h2 className="section-title">A calm, methodical look at what&apos;s happening inside.</h2><p className="body-copy">Mold concerns are rarely just about one spot on a wall. They can involve water entry, humidity, building materials, ventilation, or a history that is not obvious at first glance.</p><p className="body-copy">Our inspections are designed to turn a vague concern into a documented picture of the property — what we observed, where moisture may be involved, what questions remain, and which next steps make sense.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="soft-card"><Sparkles size={19} className="text-[#d9683e]" /><div className="mt-4 font-semibold">Evidence over alarm</div><p className="mt-2 text-sm leading-6 text-[#6d7d72]">Straightforward observations without dramatic assumptions.</p></div><div className="soft-card"><FileText size={19} className="text-[#d9683e]" /><div className="mt-4 font-semibold">Reports you can use</div><p className="mt-2 text-sm leading-6 text-[#6d7d72]">A clean summary for your next conversation or decision.</p></div></div></div></div></section>

    <section id="services" className="section-pad bg-[#e6ebe4]"><div className="container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> Focused services</div><h2 className="section-title max-w-2xl">Choose the inspection that answers the question you have.</h2></div><Link href="/mold-inspection-sacramento-ca" className="text-link">View all Sacramento services <ArrowRight size={16} /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{services.map(({ icon: Icon, title, copy, href, accent }, index) => <Link key={title} href={href} className={`service-card service-card-${accent} group`}><div className="flex items-start justify-between"><span className="service-icon"><Icon size={22} /></span><span className="text-xs font-bold text-[#809187]">0{index + 1}</span></div><h3 className="mt-16 font-display text-2xl font-semibold tracking-[-.04em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66776d]">{copy}</p><div className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#19352d]">Learn more <ArrowRight size={15} className="transition group-hover:translate-x-1" /></div></Link>)}</div></div></section>

    <section className="section-pad"><div className="container grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr] lg:gap-24"><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> Indoor air quality</div><h2 className="section-title">The air is part of the story.</h2><p className="body-copy">A home can look clean and still have questions worth investigating. We help you think through air-quality concerns, sampling options, ventilation, humidity, and the building conditions around them.</p><div className="mt-8 space-y-4">{["Talk through the concern before choosing a test", "Connect readings to the property’s visible conditions", "Document observations in plain language", "Keep the next step practical and proportional"].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-semibold"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#e6ebe4] text-[#d9683e]"><Check size={14} /></span>{item}</div>)}</div><Link href="/indoor-air-quality-sacramento-ca" className="button-secondary mt-9">Explore indoor air quality <ArrowRight size={16} /></Link></div><div className="relative"><div className="absolute -bottom-5 -left-5 h-32 w-32 rounded-full bg-[#d9a66a]/25 blur-2xl" /><img src={airImage} alt="Indoor air quality monitor beside a houseplant" className="relative aspect-[4/3] rounded-[28px] object-cover shadow-[0_25px_70px_rgba(25,53,45,.14)]" /></div></div></section>

    <section className="section-pad bg-[#19352d] text-[#f6f5f0]"><div className="container"><div className="max-w-2xl"><div className="eyebrow text-[#d9a66a]"><span className="h-px w-8 bg-[#d9a66a]" /> When to call</div><h2 className="section-title text-[#f6f5f0]">Small clues can deserve a closer look.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-[#c7d4ca]">You do not need to diagnose the issue before calling. Bring the question; we&apos;ll help define the inspection.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3"><div className="dark-card"><Droplets size={22} className="text-[#d9a66a]" /><h3 className="mt-6 font-display text-2xl font-semibold">There&apos;s been water</h3><p className="mt-3 text-sm leading-6 text-[#b7c9ba]">A leak, overflow, storm event, or damp area may have changed the moisture story.</p></div><div className="dark-card"><Wind size={22} className="text-[#d9a66a]" /><h3 className="mt-6 font-display text-2xl font-semibold">The space feels different</h3><p className="mt-3 text-sm leading-6 text-[#b7c9ba]">Odors, humidity, or recurring irritation can prompt a careful look at the environment.</p></div><div className="dark-card"><HomeIcon size={22} className="text-[#d9a66a]" /><h3 className="mt-6 font-display text-2xl font-semibold">You&apos;re making a decision</h3><p className="mt-3 text-sm leading-6 text-[#b7c9ba]">Buying, selling, renovating, or reopening a space? Document the conditions before you move forward.</p></div></div></div></section>

    <section id="process" className="section-pad"><div className="container"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> A better inspection experience</div><h2 className="section-title">Simple steps. Thorough thinking.</h2><p className="body-copy">A good inspection should feel organized from the first call to the final report.</p><a href={`tel:${PHONE}`} className="button-primary mt-8">Speak with an inspector <Phone size={16} /></a></div><div className="space-y-0">{[["01", "Start with the story", "We listen for the timeline, symptoms of the space, property history, and the decision in front of you."], ["02", "Look at the whole condition", "We review accessible areas, building materials, moisture indicators, ventilation clues, and visible concerns."], ["03", "Document what matters", "Photos, measurements, and notes are organized so the findings have context rather than standing alone."], ["04", "Leave with a next step", "You get a clear summary of what was observed and which follow-up conversations may be appropriate."]].map(([number, title, copy]) => <div key={number} className="process-row"><span className="process-number">{number}</span><div><h3 className="font-display text-2xl font-semibold tracking-[-.04em]">{title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-[#6d7d72]">{copy}</p></div></div>)}</div></div></div></section>

    <section className="section-pad bg-[#d9a66a]"><div className="container grid items-center gap-10 md:grid-cols-[1fr_auto] md:gap-16"><div><div className="eyebrow text-[#19352d]"><span className="h-px w-8 bg-[#19352d]" /> Built for clarity</div><h2 className="section-title text-[#19352d]">What you can expect from the report.</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-[#365344]">A practical record of observations, accessible areas reviewed, moisture context, photos, and questions to carry into the next step.</p></div><Link href="/mold-inspection-report-sacramento-ca" className="button-dark">See reporting details <ArrowRight size={16} /></Link></div></section>

    <section id="areas" className="section-pad"><div className="container grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> Local service area</div><h2 className="section-title">Sacramento is home base.</h2><p className="body-copy">From established neighborhoods to newer construction, local context matters. We serve Sacramento first, with inspection appointments available in nearby communities.</p><a href="https://maps.app.goo.gl/zbcc3TAXiGT8zPJp6" target="_blank" rel="noreferrer" className="text-link mt-6">2848 Arden Wy, Sacramento, CA 95825 <ArrowRight size={16} /></a></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{areas.map((area) => <div key={area} className="rounded-2xl border border-[#19352d]/10 bg-white/60 px-4 py-5 text-sm font-semibold text-[#365344]">{area}</div>)}</div></div></section>

    <section className="section-pad border-y border-[#19352d]/10 bg-[#eef0e9]"><div className="container"><div className="mx-auto max-w-3xl text-center"><div className="eyebrow justify-center"><span className="h-px w-8 bg-[#d9683e]" /> The experience we aim for</div><h2 className="section-title">Clear answers, respectful rooms, no unnecessary drama.</h2><p className="mt-5 text-lg leading-8 text-[#6d7d72]">We believe the best inspection leaves you better equipped to decide what to do next. That means careful work, plain language, and room for questions.</p></div><div className="mx-auto mt-10 grid max-w-5xl gap-4 md:grid-cols-3"><div className="quote-card"><div className="quote-mark">“</div><p>Findings should be specific enough to act on, and measured enough to trust.</p><span>Our inspection standard</span></div><div className="quote-card"><div className="quote-mark">“</div><p>Every property has a story. The inspection is how we learn to read it.</p><span>Our field approach</span></div><div className="quote-card"><div className="quote-mark">“</div><p>A useful report respects both the evidence and the person making the decision.</p><span>Our reporting promise</span></div></div></div></section>

    <section id="faq" className="section-pad"><div className="container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> Questions, answered</div><h2 className="section-title">Start where the uncertainty is.</h2><p className="body-copy">If your question is not here, call the inspection desk. We can help you decide what information would be most useful.</p></div><div className="space-y-3">{[["What does a mold inspection include?", "We begin with your concern, then review accessible areas, visible conditions, moisture indicators, and related building clues. The scope is documented in a written summary with photos and context."], ["Do you offer mold testing?", "Testing can be useful when it answers a specific question. We can discuss whether air or surface sampling is appropriate for the situation rather than treating every concern the same way."], ["Can you inspect after water damage?", "Yes. A post-water-event inspection can help document visible conditions, moisture patterns, and areas that may deserve monitoring or follow-up."], ["How quickly can I schedule?", "Call +1 916-665-4249 with the property type, location, and concern. We will discuss available timing and the most sensible inspection path."], ["Do I need to prepare the property?", "Make the areas of concern accessible if possible, gather any leak or renovation timeline you have, and let us know about rooms that may need special access planning."]].map(([question, answer]) => <details key={question} className="faq-item"><summary>{question}<ChevronDown size={19} /></summary><p>{answer}</p></details>)}</div></div></section>

    <section id="contact" className="section-pad bg-[#e6ebe4]"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[28px] bg-[#19352d] p-8 text-[#f6f5f0] sm:p-10"><div className="eyebrow text-[#d9a66a]"><span className="h-px w-8 bg-[#d9a66a]" /> Contact the inspection desk</div><h2 className="mt-6 font-display text-4xl font-semibold leading-[1.02] tracking-[-.055em] sm:text-5xl">Bring the question. We&apos;ll bring the method.</h2><p className="mt-5 text-base leading-7 text-[#c7d4ca]">Call to talk through the property, the concern, and the kind of information you need.</p><a href={`tel:${PHONE}`} className="button-accent mt-8"><Phone size={17} /> Call {DISPLAY_PHONE}</a><div className="mt-9 border-t border-white/15 pt-6 text-sm text-[#b7c9ba]">2848 Arden Wy<br />Sacramento, CA 95825</div></div><div className="min-h-[360px] overflow-hidden rounded-[28px] border border-[#19352d]/10 bg-white shadow-[0_20px_55px_rgba(25,53,45,.1)]"><iframe title="Map showing Sactown Mold's Inspections in Sacramento" src="https://www.google.com/maps?q=2848+Arden+Wy,+Sacramento,+CA+95825&output=embed" className="h-full min-h-[360px] w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></section>
  </>;
}

function ArrowUpRightIcon() { return <ArrowRight size={16} />; }
