import { Link } from "wouter";
import { ArrowRight, Check, ChevronDown, MapPin, Phone } from "lucide-react";
import Seo from "@/components/Seo";
import { DISPLAY_PHONE, PHONE } from "@/components/SiteShell";

type Location = { name: string; slug: string; path: string; title: string; intro: string; context: string; neighborhoods: string[]; concerns: string[]; faqs: [string, string][] };
const locations: Record<string, Location> = {
  "midtown-sacramento": { name: "Midtown Sacramento", slug: "midtown-sacramento", path: "/mold-inspection-midtown-sacramento-ca", title: "Mold Inspection Midtown Sacramento CA | Sactown Mold's Inspections", intro: "Mold inspection for Midtown Sacramento homes, apartments, and properties with questions about moisture, air quality, or recurring indoor conditions.", context: "Midtown’s mix of historic homes, remodels, apartments, and close-in urban blocks means each inspection starts with the property’s own story. Older materials, recent improvements, crawl spaces, and shared walls can all shape the question.", neighborhoods: ["Marshall School", "Newton Booth", "Southside Park", "Boulevard Park", "Alkali Flat", "East Sacramento edge"], concerns: ["Older plumbing and past leaks", "Remodeled kitchens and baths", "Humidity and ventilation questions", "Recurring odor or staining"], faqs: [["Do you inspect apartments in Midtown?", "We can discuss access, occupancy, and property-management coordination when scheduling a residential inspection."], ["Can you look at an older Sacramento home?", "Yes. The property age and renovation history are useful context for deciding what to review."], ["Do I need a full-home inspection?", "Not always. We can talk through whether a focused room or whole-home scope fits your concern."]] },
  "east-sacramento": { name: "East Sacramento", slug: "east-sacramento", path: "/mold-inspection-east-sacramento-ca", title: "Mold Inspection East Sacramento CA | Sactown Mold's Inspections", intro: "Thoughtful mold and moisture inspections for East Sacramento homes, renovations, and property decisions.", context: "East Sacramento properties can include established homes, additions, mature landscaping, and renovation histories that make moisture pathways worth understanding in context.", neighborhoods: ["East Sacramento", "River Park", "Campus Commons", "Tahoe Park", "Elmhurst", "Hagginwood edge"], concerns: ["Roof and exterior-wall moisture", "Additions and transitions", "Attic or crawl-space questions", "Water history after storms or repairs"], faqs: [["Can you inspect after a renovation?", "Yes. Share the renovation timing and any areas that changed, so the scope can reflect the work completed."], ["Do you inspect attics and crawl spaces?", "Accessible attics and crawl spaces can be included when conditions allow a safe review."], ["Can the report support a property decision?", "The report is designed to document observations and context for your next conversation with the relevant property professional."]] },
  "arden-arcade": { name: "Arden-Arcade", slug: "arden-arcade", path: "/mold-inspection-arden-arcade-ca", title: "Mold Inspection Arden-Arcade CA | Sactown Mold's Inspections", intro: "Local mold inspection and indoor-environment guidance for Arden-Arcade properties near Sacramento.", context: "Arden-Arcade includes a wide range of homes, commercial spaces, and property eras. A clear scope helps separate a visible concern from the building conditions around it.", neighborhoods: ["Arden-Arcade", "Arden Park", "Wilhaggin", "Del Paso Manor", "Fulton Avenue corridor", "Swanston Estates"], concerns: ["HVAC and ventilation clues", "Bathrooms and plumbing areas", "Past water intrusion", "Indoor air quality questions"], faqs: [["Is your office in Arden-Arcade?", "The primary location is 2848 Arden Wy, Sacramento, CA 95825. Call to discuss an appointment for your property."], ["Can you help with commercial properties?", "Call with the property type, access requirements, and concern so the inspection scope can be discussed."], ["Do you test for mold?", "Testing may be useful for a specific question. We can talk through inspection and sampling options before scheduling."]] },
  "citrus-heights": { name: "Citrus Heights", slug: "citrus-heights", path: "/mold-inspection-citrus-heights-ca", title: "Mold Inspection Citrus Heights CA | Sactown Mold's Inspections", intro: "Mold, moisture, and indoor air quality inspection support for Citrus Heights homes and property teams.", context: "Citrus Heights homes may bring together older construction, remodels, sloped lots, garages, and attic spaces. The inspection is about following the condition across accessible areas.", neighborhoods: ["Citrus Heights", "Sylvan Corners", "Birdcage Heights", "Arcade Creek", "Roseville Road corridor", "Antelope edge"], concerns: ["Garage and utility-space moisture", "Attic ventilation", "Past plumbing events", "Recurring staining or odor"], faqs: [["Can you inspect a home after a leak?", "Yes. A post-water-event scope can document accessible conditions, moisture context, and questions for repair or remediation."], ["Do you serve landlords?", "Yes. Call with the property type, access details, and the decision the documentation needs to support."], ["How do I start?", "Call +1 916-665-4249 and describe what you are noticing. We will help you choose a reasonable next step."]] },
  "elk-grove": { name: "Elk Grove", slug: "elk-grove", path: "/mold-inspection-elk-grove-ca", title: "Mold Inspection Elk Grove CA | Sactown Mold's Inspections", intro: "Clear mold and moisture inspections for Elk Grove homes, buyers, sellers, and property managers.", context: "Elk Grove’s newer and established neighborhoods can have different inspection questions: construction transitions, HVAC operation, bathroom moisture, and the history of repairs or occupancy.", neighborhoods: ["Elk Grove", "Laguna", "Laguna West", "Stonelake", "Cosumnes River", "Vineyard edge"], concerns: ["Newer construction moisture clues", "HVAC and condensation", "Bathroom and laundry areas", "Buyer or seller documentation"], faqs: [["Do you inspect newer homes?", "Yes. Newer construction still has a building story, and the inspection scope can reflect the concern and property history."], ["Can you inspect before listing?", "Call to discuss timing and the documentation you want available for your property decision."], ["Are health claims included in the report?", "No. Reports describe property and indoor-environment observations rather than making medical conclusions."]] },
  "roseville": { name: "Roseville", slug: "roseville", path: "/mold-inspection-roseville-ca", title: "Mold Inspection Roseville CA | Sactown Mold's Inspections", intro: "Professional mold inspection support for Roseville homes, remodels, and indoor-environment concerns.", context: "Roseville properties span established neighborhoods, newer developments, remodels, and larger floor plans. A good scope is specific about areas, access, and the decision in front of you.", neighborhoods: ["Roseville", "West Roseville", "East Roseville", "Cresthaven", "Johnson Ranch", "Woodcreek"], concerns: ["Large-home moisture patterns", "Remodel and addition transitions", "Attic and crawl-space conditions", "Indoor air quality questions"], faqs: [["Can you inspect a larger home?", "Yes. Tell us the approximate size, number of areas, and concern when scheduling so the visit can be planned appropriately."], ["Can you review an attic or crawl space?", "Accessible areas can be considered when conditions allow a safe and useful review."], ["Can I schedule by phone?", "Yes. Call +1 916-665-4249 to discuss the property and available timing."]] },
  "folsom": { name: "Folsom", slug: "folsom", path: "/mold-inspection-folsom-ca", title: "Mold Inspection Folsom CA | Sactown Mold's Inspections", intro: "Mold inspection, moisture investigation, and indoor-environment guidance for Folsom properties.", context: "Folsom homes can vary from established neighborhoods to newer construction and remodels. The right inspection connects the visible question to the spaces and systems around it.", neighborhoods: ["Folsom", "Historic Folsom", "Broadstone", "Empire Ranch", "American River Canyon", "Lakehills"], concerns: ["Exterior and roof-water questions", "Bathrooms, laundry, and kitchens", "New construction transitions", "Property transaction documentation"], faqs: [["Do you inspect for buyers in Folsom?", "A mold-focused inspection can complement a general home inspection when there is a specific concern or history to investigate."], ["Can you document a past water event?", "Yes. Share the event timeline and we can discuss an appropriate post-water inspection scope."], ["What should I do before the visit?", "Keep the concern accessible, avoid disturbing it if possible, and gather any relevant leak, repair, or renovation history."]] },
  "fair-oaks": { name: "Fair Oaks", slug: "fair-oaks", path: "/mold-inspection-fair-oaks-ca", title: "Mold Inspection Fair Oaks CA | Sactown Mold's Inspections", intro: "Focused mold, moisture, and indoor air quality inspections for Fair Oaks properties near Sacramento.", context: "Fair Oaks properties can include mature landscaping, varied grades, older homes, additions, and spaces where moisture behaves differently from the living area.", neighborhoods: ["Fair Oaks", "Rollingwood", "Phoenix Field", "Northridge", "Walnut Creek", "Orangevale edge"], concerns: ["Crawl-space and ground moisture", "Mature-tree and exterior drainage clues", "Older plumbing or roof history", "Recurring odor or staining"], faqs: [["Do you inspect crawl spaces in Fair Oaks?", "Accessible crawl spaces can be included when clearance and conditions allow a safe review."], ["Can you inspect after exterior drainage work?", "Yes. Share what changed and when so the inspection can document the current condition and remaining questions."], ["How do I book an appointment?", "Call the inspection desk at +1 916-665-4249 with the address, property type, and concern."]] },
};

export default function LocationPage({ slug }: { slug: string }) {
  const location = locations[slug] ?? locations["midtown-sacramento"];
  const inspectorPage = window.location.pathname.includes("/mold-inspector-");
  const pagePath = inspectorPage ? location.path.replace("/mold-inspection-", "/mold-inspector-") : location.path;
  const pageTitle = inspectorPage ? `Mold Inspector ${location.name} CA | Sactown Mold's Inspections` : location.title;
  const pageH1 = inspectorPage ? `A mold inspector for ${location.name}` : `Mold inspection in ${location.name}`;
  const schema = { "@context": "https://schema.org", "@type": "Service", name: pageH1, description: location.intro, provider: { "@type": "ProfessionalService", name: "Sactown Mold's Inspections", telephone: DISPLAY_PHONE, address: { "@type": "PostalAddress", streetAddress: "2848 Arden Wy", addressLocality: "Sacramento", addressRegion: "CA", postalCode: "95825", addressCountry: "US" } }, areaServed: location.name };
  return <>
    <Seo title={pageTitle} description={location.intro} path={pagePath} schema={schema} />
    <section className="bg-[#19352d] text-[#f6f5f0]"><div className="container py-20 sm:py-28"><div className="max-w-3xl"><div className="eyebrow text-[#d9a66a]"><span className="h-px w-8 bg-[#d9a66a]" /> Serving nearby Sacramento communities</div><h1 className="mt-7 font-display text-5xl font-semibold leading-[.98] tracking-[-.065em] sm:text-7xl">{pageH1}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#d5e0d5]">{location.intro}</p><a href={`tel:${PHONE}`} className="button-accent mt-9"><Phone size={17} /> Call now · {DISPLAY_PHONE}</a></div></div></section>
    <section className="section-pad"><div className="container grid gap-14 lg:grid-cols-[.85fr_1.15fr] lg:gap-24"><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> Local context</div><h2 className="section-title">A property-specific look, close to home.</h2><p className="body-copy">{location.context}</p><div className="mt-8 flex items-start gap-3 rounded-2xl bg-[#e6ebe4] p-5 text-sm leading-6 text-[#365344]"><MapPin size={18} className="mt-1 shrink-0 text-[#d9683e]" /> Primary location: 2848 Arden Wy, Sacramento, CA 95825</div></div><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> Common questions in {location.name}</div><div className="mt-6 grid gap-3 sm:grid-cols-2">{location.concerns.map((item) => <div key={item} className="rounded-2xl border border-[#19352d]/10 bg-[#eef0e9] p-5 text-sm font-semibold"><Check size={17} className="mb-4 text-[#d9683e]" />{item}</div>)}</div></div></div></section>
    <section className="section-pad bg-[#e6ebe4]"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> Areas we know</div><h2 className="section-title">Neighborhood context helps.</h2><p className="body-copy">Every appointment is scoped to the property, but these are some of the nearby communities we regularly think about when planning access and travel.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{location.neighborhoods.map((area) => <div key={area} className="rounded-2xl bg-[#f6f5f0] px-4 py-5 text-sm font-semibold text-[#365344] shadow-sm">{area}</div>)}</div></div></section>
    <section className="section-pad"><div className="container grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="eyebrow"><span className="h-px w-8 bg-[#d9683e]" /> Plan the visit</div><h2 className="section-title">Start with the question you want answered.</h2><p className="body-copy">We serve Sacramento first and schedule nearby appointments based on property type, concern, scope, and timing.</p><a href={`tel:${PHONE}`} className="button-primary mt-8"><Phone size={16} /> Speak with an inspector</a></div><div className="space-y-3">{location.faqs.map(([question, answer]) => <details key={question} className="faq-item"><summary>{question}<ChevronDown size={19} /></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="section-pad bg-[#19352d] text-[#f6f5f0]"><div className="container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="eyebrow text-[#d9a66a]"><span className="h-px w-8 bg-[#d9a66a]" /> Explore the main location</div><h2 className="mt-5 font-display text-4xl font-semibold tracking-[-.055em] sm:text-5xl">See Sacramento inspection services.</h2></div><Link href="/mold-inspection-sacramento-ca" className="button-accent">View Sacramento services <ArrowRight size={16} /></Link></div></div></section>
  </>;
}

export { locations };
